# Generated by Django 2.2 on 2020-02-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200223_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=150)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_payment_method', to='store.Store')),
            ],
        ),
    ]
