# Generated by Django 2.2 on 2020-02-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
