# Generated by Django 2.2 on 2020-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200222_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Your Country', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Your State', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='Zip Code', max_length=150),
        ),
    ]
