# Generated by Django 2.2 on 2020-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_count',
            field=models.CharField(default='xxx', max_length=255),
            preserve_default=False,
        ),
    ]
