# Generated by Django 2.2 on 2020-02-26 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_auto_20200226_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_seller',
            field=models.CharField(default='XXXXXXXXXXXXXXXXXXXXX', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
