# Generated by Django 2.2 on 2020-02-26 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_auto_20200226_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ManyToManyField(blank=True, null=True, related_name='seller_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
