# Generated by Django 2.2 on 2020-02-28 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200226_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='payment_methods/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='sellers',
            field=models.ManyToManyField(related_name='seller_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
